/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientChatRouteImport } from './routes/patient.chat'
import { Route as PatientDoctorsRouteImport } from './routes/patient.doctors'
import { Route as PatientDoctorsDoctorIdRouteImport } from './routes/patient.doctors.$doctorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientChatRoute = PatientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDoctorsDoctorIdRoute = PatientDoctorsDoctorIdRouteImport.update({
  id: '/$doctorId',
  path: '/$doctorId',
  getParentRoute: () => PatientDoctorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/patient': typeof PatientRouteWithChildren
  '/signup': typeof SignupRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/': typeof PatientIndexRoute
  '/patient/doctors/$doctorId': typeof PatientDoctorsDoctorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signup': typeof SignupRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient': typeof PatientIndexRoute
  '/patient/doctors/$doctorId': typeof PatientDoctorsDoctorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/patient': typeof PatientRouteWithChildren
  '/signup': typeof SignupRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/': typeof PatientIndexRoute
  '/patient/doctors/$doctorId': typeof PatientDoctorsDoctorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/forgot-password'
    | '/patient'
    | '/signup'
    | '/patient/chat'
    | '/patient/doctors'
    | '/patient/'
    | '/patient/doctors/$doctorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor'
    | '/forgot-password'
    | '/signup'
    | '/patient/chat'
    | '/patient/doctors'
    | '/patient'
    | '/patient/doctors/$doctorId'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/forgot-password'
    | '/patient'
    | '/signup'
    | '/patient/chat'
    | '/patient/doctors'
    | '/patient/'
    | '/patient/doctors/$doctorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PatientRoute: typeof PatientRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/chat': {
      id: '/patient/chat'
      path: '/chat'
      fullPath: '/patient/chat'
      preLoaderRoute: typeof PatientChatRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/doctors/$doctorId': {
      id: '/patient/doctors/$doctorId'
      path: '/$doctorId'
      fullPath: '/patient/doctors/$doctorId'
      preLoaderRoute: typeof PatientDoctorsDoctorIdRouteImport
      parentRoute: typeof PatientDoctorsRoute
    }
  }
}

interface PatientDoctorsRouteChildren {
  PatientDoctorsDoctorIdRoute: typeof PatientDoctorsDoctorIdRoute
}

const PatientDoctorsRouteChildren: PatientDoctorsRouteChildren = {
  PatientDoctorsDoctorIdRoute: PatientDoctorsDoctorIdRoute,
}

const PatientDoctorsRouteWithChildren = PatientDoctorsRoute._addFileChildren(
  PatientDoctorsRouteChildren,
)

interface PatientRouteChildren {
  PatientChatRoute: typeof PatientChatRoute
  PatientDoctorsRoute: typeof PatientDoctorsRouteWithChildren
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientChatRoute: PatientChatRoute,
  PatientDoctorsRoute: PatientDoctorsRouteWithChildren,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PatientRoute: PatientRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
