/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminSynthflowRouteImport } from './routes/admin.synthflow'
import { Route as AdminVoiceCallsRouteImport } from './routes/admin.voice-calls'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorActivityRouteImport } from './routes/doctor.activity'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor.availability'
import { Route as DoctorNotificationsRouteImport } from './routes/doctor.notifications'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorRecordsRouteImport } from './routes/doctor.records'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientActivityRouteImport } from './routes/patient.activity'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as PatientBookRouteImport } from './routes/patient.book'
import { Route as PatientChatRouteImport } from './routes/patient.chat'
import { Route as PatientConfirmationRouteImport } from './routes/patient.confirmation'
import { Route as PatientDoctorsRouteImport } from './routes/patient.doctors'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientMessagesRouteImport } from './routes/patient.messages'
import { Route as PatientRecordsRouteImport } from './routes/patient.records'
import { Route as AdminDoctorsUserIdRouteImport } from './routes/admin.doctors.$userId'
import { Route as AdminPatientsUserIdRouteImport } from './routes/admin.patients.$userId'
import { Route as DoctorPatientsPatientIdRouteImport } from './routes/doctor.patients.$patientId'
import { Route as PatientAppointmentsAppointmentIdRouteImport } from './routes/patient.appointments.$appointmentId'
import { Route as PatientDoctorsDoctorIdRouteImport } from './routes/patient.doctors.$doctorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSynthflowRoute = AdminSynthflowRouteImport.update({
  id: '/synthflow',
  path: '/synthflow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoiceCallsRoute = AdminVoiceCallsRouteImport.update({
  id: '/voice-calls',
  path: '/voice-calls',
  getParentRoute: () => AdminRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorActivityRoute = DoctorActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorNotificationsRoute = DoctorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorRecordsRoute = DoctorRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientActivityRoute = PatientActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PatientRoute,
} as any)
const PatientChatRoute = PatientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PatientRoute,
} as any)
const PatientConfirmationRoute = PatientConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMessagesRoute = PatientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientRoute,
} as any)
const PatientRecordsRoute = PatientRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => PatientRoute,
} as any)
const AdminDoctorsUserIdRoute = AdminDoctorsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminDoctorsRoute,
} as any)
const AdminPatientsUserIdRoute = AdminPatientsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const DoctorPatientsPatientIdRoute = DoctorPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => DoctorPatientsRoute,
} as any)
const PatientAppointmentsAppointmentIdRoute =
  PatientAppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => PatientAppointmentsRoute,
  } as any)
const PatientDoctorsDoctorIdRoute = PatientDoctorsDoctorIdRouteImport.update({
  id: '/$doctorId',
  path: '/$doctorId',
  getParentRoute: () => PatientDoctorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/patient': typeof PatientRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/synthflow': typeof AdminSynthflowRoute
  '/admin/voice-calls': typeof AdminVoiceCallsRoute
  '/doctor/activity': typeof DoctorActivityRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/activity': typeof PatientActivityRoute
  '/patient/appointments': typeof PatientAppointmentsRouteWithChildren
  '/patient/book': typeof PatientBookRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/confirmation': typeof PatientConfirmationRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/history': typeof PatientHistoryRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/records': typeof PatientRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/admin/doctors/$userId': typeof AdminDoctorsUserIdRoute
  '/admin/patients/$userId': typeof AdminPatientsUserIdRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/patient/appointments/$appointmentId': typeof PatientAppointmentsAppointmentIdRoute
  '/patient/doctors/$doctorId': typeof PatientDoctorsDoctorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/synthflow': typeof AdminSynthflowRoute
  '/admin/voice-calls': typeof AdminVoiceCallsRoute
  '/doctor/activity': typeof DoctorActivityRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/activity': typeof PatientActivityRoute
  '/patient/appointments': typeof PatientAppointmentsRouteWithChildren
  '/patient/book': typeof PatientBookRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/confirmation': typeof PatientConfirmationRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/history': typeof PatientHistoryRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/records': typeof PatientRecordsRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/admin/doctors/$userId': typeof AdminDoctorsUserIdRoute
  '/admin/patients/$userId': typeof AdminPatientsUserIdRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/patient/appointments/$appointmentId': typeof PatientAppointmentsAppointmentIdRoute
  '/patient/doctors/$doctorId': typeof PatientDoctorsDoctorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/patient': typeof PatientRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/synthflow': typeof AdminSynthflowRoute
  '/admin/voice-calls': typeof AdminVoiceCallsRoute
  '/doctor/activity': typeof DoctorActivityRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/patient/activity': typeof PatientActivityRoute
  '/patient/appointments': typeof PatientAppointmentsRouteWithChildren
  '/patient/book': typeof PatientBookRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/confirmation': typeof PatientConfirmationRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/history': typeof PatientHistoryRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/records': typeof PatientRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/admin/doctors/$userId': typeof AdminDoctorsUserIdRoute
  '/admin/patients/$userId': typeof AdminPatientsUserIdRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/patient/appointments/$appointmentId': typeof PatientAppointmentsAppointmentIdRoute
  '/patient/doctors/$doctorId': typeof PatientDoctorsDoctorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/forgot-password'
    | '/patient'
    | '/reset-password'
    | '/signup'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/patients'
    | '/admin/synthflow'
    | '/admin/voice-calls'
    | '/doctor/activity'
    | '/doctor/availability'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/records'
    | '/doctor/schedule'
    | '/patient/activity'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/chat'
    | '/patient/confirmation'
    | '/patient/doctors'
    | '/patient/history'
    | '/patient/messages'
    | '/patient/records'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/admin/doctors/$userId'
    | '/admin/patients/$userId'
    | '/doctor/patients/$patientId'
    | '/patient/appointments/$appointmentId'
    | '/patient/doctors/$doctorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/patients'
    | '/admin/synthflow'
    | '/admin/voice-calls'
    | '/doctor/activity'
    | '/doctor/availability'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/records'
    | '/doctor/schedule'
    | '/patient/activity'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/chat'
    | '/patient/confirmation'
    | '/patient/doctors'
    | '/patient/history'
    | '/patient/messages'
    | '/patient/records'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/admin/doctors/$userId'
    | '/admin/patients/$userId'
    | '/doctor/patients/$patientId'
    | '/patient/appointments/$appointmentId'
    | '/patient/doctors/$doctorId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/forgot-password'
    | '/patient'
    | '/reset-password'
    | '/signup'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/patients'
    | '/admin/synthflow'
    | '/admin/voice-calls'
    | '/doctor/activity'
    | '/doctor/availability'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/records'
    | '/doctor/schedule'
    | '/patient/activity'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/chat'
    | '/patient/confirmation'
    | '/patient/doctors'
    | '/patient/history'
    | '/patient/messages'
    | '/patient/records'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/admin/doctors/$userId'
    | '/admin/patients/$userId'
    | '/doctor/patients/$patientId'
    | '/patient/appointments/$appointmentId'
    | '/patient/doctors/$doctorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PatientRoute: typeof PatientRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/synthflow': {
      id: '/admin/synthflow'
      path: '/synthflow'
      fullPath: '/admin/synthflow'
      preLoaderRoute: typeof AdminSynthflowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voice-calls': {
      id: '/admin/voice-calls'
      path: '/voice-calls'
      fullPath: '/admin/voice-calls'
      preLoaderRoute: typeof AdminVoiceCallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/activity': {
      id: '/doctor/activity'
      path: '/activity'
      fullPath: '/doctor/activity'
      preLoaderRoute: typeof DoctorActivityRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/availability': {
      id: '/doctor/availability'
      path: '/availability'
      fullPath: '/doctor/availability'
      preLoaderRoute: typeof DoctorAvailabilityRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/notifications': {
      id: '/doctor/notifications'
      path: '/notifications'
      fullPath: '/doctor/notifications'
      preLoaderRoute: typeof DoctorNotificationsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/records': {
      id: '/doctor/records'
      path: '/records'
      fullPath: '/doctor/records'
      preLoaderRoute: typeof DoctorRecordsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/activity': {
      id: '/patient/activity'
      path: '/activity'
      fullPath: '/patient/activity'
      preLoaderRoute: typeof PatientActivityRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/chat': {
      id: '/patient/chat'
      path: '/chat'
      fullPath: '/patient/chat'
      preLoaderRoute: typeof PatientChatRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/confirmation': {
      id: '/patient/confirmation'
      path: '/confirmation'
      fullPath: '/patient/confirmation'
      preLoaderRoute: typeof PatientConfirmationRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/messages': {
      id: '/patient/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientMessagesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/records': {
      id: '/patient/records'
      path: '/records'
      fullPath: '/patient/records'
      preLoaderRoute: typeof PatientRecordsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/admin/doctors/$userId': {
      id: '/admin/doctors/$userId'
      path: '/$userId'
      fullPath: '/admin/doctors/$userId'
      preLoaderRoute: typeof AdminDoctorsUserIdRouteImport
      parentRoute: typeof AdminDoctorsRoute
    }
    '/admin/patients/$userId': {
      id: '/admin/patients/$userId'
      path: '/$userId'
      fullPath: '/admin/patients/$userId'
      preLoaderRoute: typeof AdminPatientsUserIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/doctor/patients/$patientId': {
      id: '/doctor/patients/$patientId'
      path: '/$patientId'
      fullPath: '/doctor/patients/$patientId'
      preLoaderRoute: typeof DoctorPatientsPatientIdRouteImport
      parentRoute: typeof DoctorPatientsRoute
    }
    '/patient/appointments/$appointmentId': {
      id: '/patient/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/patient/appointments/$appointmentId'
      preLoaderRoute: typeof PatientAppointmentsAppointmentIdRouteImport
      parentRoute: typeof PatientAppointmentsRoute
    }
    '/patient/doctors/$doctorId': {
      id: '/patient/doctors/$doctorId'
      path: '/$doctorId'
      fullPath: '/patient/doctors/$doctorId'
      preLoaderRoute: typeof PatientDoctorsDoctorIdRouteImport
      parentRoute: typeof PatientDoctorsRoute
    }
  }
}

interface AdminDoctorsRouteChildren {
  AdminDoctorsUserIdRoute: typeof AdminDoctorsUserIdRoute
}

const AdminDoctorsRouteChildren: AdminDoctorsRouteChildren = {
  AdminDoctorsUserIdRoute: AdminDoctorsUserIdRoute,
}

const AdminDoctorsRouteWithChildren = AdminDoctorsRoute._addFileChildren(
  AdminDoctorsRouteChildren,
)

interface AdminPatientsRouteChildren {
  AdminPatientsUserIdRoute: typeof AdminPatientsUserIdRoute
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsUserIdRoute: AdminPatientsUserIdRoute,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminSynthflowRoute: typeof AdminSynthflowRoute
  AdminVoiceCallsRoute: typeof AdminVoiceCallsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminSynthflowRoute: AdminSynthflowRoute,
  AdminVoiceCallsRoute: AdminVoiceCallsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorPatientsRouteChildren {
  DoctorPatientsPatientIdRoute: typeof DoctorPatientsPatientIdRoute
}

const DoctorPatientsRouteChildren: DoctorPatientsRouteChildren = {
  DoctorPatientsPatientIdRoute: DoctorPatientsPatientIdRoute,
}

const DoctorPatientsRouteWithChildren = DoctorPatientsRoute._addFileChildren(
  DoctorPatientsRouteChildren,
)

interface DoctorRouteChildren {
  DoctorActivityRoute: typeof DoctorActivityRoute
  DoctorAvailabilityRoute: typeof DoctorAvailabilityRoute
  DoctorNotificationsRoute: typeof DoctorNotificationsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRouteWithChildren
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorRecordsRoute: typeof DoctorRecordsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorActivityRoute: DoctorActivityRoute,
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
  DoctorNotificationsRoute: DoctorNotificationsRoute,
  DoctorPatientsRoute: DoctorPatientsRouteWithChildren,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorRecordsRoute: DoctorRecordsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientAppointmentsRouteChildren {
  PatientAppointmentsAppointmentIdRoute: typeof PatientAppointmentsAppointmentIdRoute
}

const PatientAppointmentsRouteChildren: PatientAppointmentsRouteChildren = {
  PatientAppointmentsAppointmentIdRoute: PatientAppointmentsAppointmentIdRoute,
}

const PatientAppointmentsRouteWithChildren =
  PatientAppointmentsRoute._addFileChildren(PatientAppointmentsRouteChildren)

interface PatientDoctorsRouteChildren {
  PatientDoctorsDoctorIdRoute: typeof PatientDoctorsDoctorIdRoute
}

const PatientDoctorsRouteChildren: PatientDoctorsRouteChildren = {
  PatientDoctorsDoctorIdRoute: PatientDoctorsDoctorIdRoute,
}

const PatientDoctorsRouteWithChildren = PatientDoctorsRoute._addFileChildren(
  PatientDoctorsRouteChildren,
)

interface PatientRouteChildren {
  PatientActivityRoute: typeof PatientActivityRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRouteWithChildren
  PatientBookRoute: typeof PatientBookRoute
  PatientChatRoute: typeof PatientChatRoute
  PatientConfirmationRoute: typeof PatientConfirmationRoute
  PatientDoctorsRoute: typeof PatientDoctorsRouteWithChildren
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientMessagesRoute: typeof PatientMessagesRoute
  PatientRecordsRoute: typeof PatientRecordsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientActivityRoute: PatientActivityRoute,
  PatientAppointmentsRoute: PatientAppointmentsRouteWithChildren,
  PatientBookRoute: PatientBookRoute,
  PatientChatRoute: PatientChatRoute,
  PatientConfirmationRoute: PatientConfirmationRoute,
  PatientDoctorsRoute: PatientDoctorsRouteWithChildren,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientMessagesRoute: PatientMessagesRoute,
  PatientRecordsRoute: PatientRecordsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PatientRoute: PatientRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
